# API Wrapper MCP Server Configuration Example

# Server info
server:
  name: "API Gateway MCP"
  description: "Generic API gateway that wraps REST APIs as MCP tools"
  version: "1.0.0"
  
# Authentication
auth:
  token_env_var: "API_GATEWAY_TOKEN"  # Environment variable for the API token

# Tool definitions
tools:
  - name: "search-web"
    description: "Search the web using Perplexity API"
    endpoint: "https://api.perplexity.ai/search"
    method: "POST"
    timeout: 30  # Request timeout in seconds
    template: |
      {
        "query": "{{query}}",
        "max_results": {{max_results}},
        "search_depth": "{{depth}}"
      }
    parameters:
      query:
        type: "string"
        description: "The search query"
        required: true
      max_results:
        type: "number"
        description: "Maximum number of results to return"
        default: 5
      depth:
        type: "string"
        description: "Search depth (basic or deep)"
        enum: ["basic", "deep"]
        default: "basic"
  
  - name: "weather-forecast"
    description: "Get weather forecast data for a location"
    endpoint: "https://api.weatherapi.com/v1/forecast.json"
    method: "GET"
    timeout: 15
    query_params:
      key: "{{env:WEATHER_API_KEY}}"  # Special syntax to use a different env var for this API
      q: "{{location}}"
      days: "{{days}}"
      aqi: "{{air_quality}}"
    parameters:
      location:
        type: "string"
        description: "Location name, zipcode, or latitude,longitude"
        required: true
      days:
        type: "number"
        description: "Number of days of forecast to return"
        default: 3
      air_quality:
        type: "string"
        description: "Include air quality data"
        enum: ["yes", "no"]
        default: "no"
